/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cogroid_atomspace_Node */

#ifndef _Included_com_cogroid_atomspace_Node
#define _Included_com_cogroid_atomspace_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cogroid_atomspace_Node
 * Method:    jni_init
 * Signature: (JILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_cogroid_atomspace_Node_jni_1init
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_cogroid_atomspace_Node
 * Method:    jni_get_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cogroid_atomspace_Node_jni_1get_1name
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_cogroid_atomspace_Node
 * Method:    jni_get_arity
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_cogroid_atomspace_Node_jni_1get_1arity
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_cogroid_atomspace_Node
 * Method:    jni_dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_cogroid_atomspace_Node_jni_1dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_cogroid_atomspace_Node
 * Method:    jni_equals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cogroid_atomspace_Node_jni_1equals
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_cogroid_atomspace_Node
 * Method:    jni_to_string
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cogroid_atomspace_Node_jni_1to_1string
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_cogroid_atomspace_Node
 * Method:    jni_to_short_string
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cogroid_atomspace_Node_jni_1to_1short_1string
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
