/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cogroid_atomspace_Atom */

#ifndef _Included_com_cogroid_atomspace_Atom
#define _Included_com_cogroid_atomspace_Atom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cogroid_atomspace_Atom
 * Method:    jni_get_hash
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_cogroid_atomspace_Atom_jni_1get_1hash
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_cogroid_atomspace_Atom
 * Method:    jni_dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_cogroid_atomspace_Atom_jni_1dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
