/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cogroid_atomspace_Value */

#ifndef _Included_com_cogroid_atomspace_Value
#define _Included_com_cogroid_atomspace_Value
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cogroid_atomspace_Value
 * Method:    jni_is_type
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cogroid_atomspace_Value_jni_1is_1type
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_cogroid_atomspace_Value
 * Method:    jni_dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_cogroid_atomspace_Value_jni_1dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
