/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cogroid_atomspace_PseudoValue */

#ifndef _Included_com_cogroid_atomspace_PseudoValue
#define _Included_com_cogroid_atomspace_PseudoValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cogroid_atomspace_PseudoValue
 * Method:    jni_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_cogroid_atomspace_PseudoValue_jni_1init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
