/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cogroid_atomspace_AtomSpace */

#ifndef _Included_com_cogroid_atomspace_AtomSpace
#define _Included_com_cogroid_atomspace_AtomSpace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cogroid_atomspace_AtomSpace
 * Method:    jni_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_cogroid_atomspace_AtomSpace_jni_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_cogroid_atomspace_AtomSpace
 * Method:    jni_dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_cogroid_atomspace_AtomSpace_jni_1dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
