
; DO NOT EDIT THIS FILE! This file was automatically
; generated from atom definitions in
; /home/cogroid/wrk/d-atomspace/i386/d-atomspace/opencog/persist/storage/storage_types.script
; by the macro OPENCOG_SCM_ATOMTYPES
;
; This file contains basic scheme wrappers for atom creation.
;
(define-public StorageNodeType (cog-type->int 'StorageNode))
(define-public (StorageNode . x)
	(apply cog-new-node (cons StorageNodeType x)))
(define-public (Storage . x)
	(apply cog-new-node (cons StorageNodeType x)))
(define-public PostgresStorageNodeType (cog-type->int 'PostgresStorageNode))
(define-public (PostgresStorageNode . x)
	(apply cog-new-node (cons PostgresStorageNodeType x)))
(define-public (PostgresStorage . x)
	(apply cog-new-node (cons PostgresStorageNodeType x)))
(define-public RocksStorageNodeType (cog-type->int 'RocksStorageNode))
(define-public (RocksStorageNode . x)
	(apply cog-new-node (cons RocksStorageNodeType x)))
(define-public (RocksStorage . x)
	(apply cog-new-node (cons RocksStorageNodeType x)))
(define-public CogSimpleStorageNodeType (cog-type->int 'CogSimpleStorageNode))
(define-public (CogSimpleStorageNode . x)
	(apply cog-new-node (cons CogSimpleStorageNodeType x)))
(define-public (CogSimpleStorage . x)
	(apply cog-new-node (cons CogSimpleStorageNodeType x)))
(define-public CogStorageNodeType (cog-type->int 'CogStorageNode))
(define-public (CogStorageNode . x)
	(apply cog-new-node (cons CogStorageNodeType x)))
(define-public (CogStorage . x)
	(apply cog-new-node (cons CogStorageNodeType x)))
(define-public FileStorageNodeType (cog-type->int 'FileStorageNode))
(define-public (FileStorageNode . x)
	(apply cog-new-node (cons FileStorageNodeType x)))
(define-public (FileStorage . x)
	(apply cog-new-node (cons FileStorageNodeType x)))
